### ISSUE TITLE
Bots causing crashes?

### ISSUE THREAD

**Issue by SeanABoyer** [shobhit-pathak/MatchZy#85]
Server keeps crashing when bots are involved. I've been able to reproduce consistently a few times now.
`5:47:06 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type, Byte* ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 451
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 379
   at CounterStrikeSharp.API.Core.NativeAPI.GetSchemaValueByName[T](IntPtr instance, Int32 returntype, String classname, String propname) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1099
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaValue[T](IntPtr handle, String className, String propertyName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 80
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetString(IntPtr pointer, String className, String memberName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 138
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_PlayerName() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 5103
   at MatchZy.MatchZy.TemporarilyDisableCollisions(CCSPlayerController p1, CCSPlayerController p2) in F:\MatchZy\PracticeMode.cs:line 815
   at MatchZy.MatchZy.<>c__DisplayClass203_1.<OnPlayerSpawn>b__1() in F:\MatchZy\PracticeMode.cs:line 892
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82`

It appears to occur consistently if you have 2 or more bots on the Server:
1. Connect to server and change to practice mode via `.prac`
2. Spawn bot #1 via `.bot`
3. Spawn bot #2 via `.bot`
4. Change the map via `.map de_ancient`
5. Server Crashes

When I only spawn 1 bot then change map, It sometimes crashes and sometimes does not.
Steps that did not reproduce error:
1. Connect to server and change to practice mode via `.prac`
2. Spawn a bot via `.bot`
3. Clear bots via `.nobots`
4. Change the map via `.map de_ancient`
6. Server Crashes

**Comment by shobhit-pathak** [comment]
Hey!

I've also seen this issue multiple times, but seems it is related to CS2 or CS#, I'm not sure if anything can be done from plugin side for this. Though, I'll recheck this issue.

Thanks!

**Comment by mortenlein** [comment]
Hello,

I did some testing on this matter, as the server kept crashing when using bots.

Setup: Metamod, Countersharp, MatchZy all updated to the newest version.

- If you add 5 bots in a cluster, and spam nades on them (.rethrownade), nothing will happen with the server, you could possible do this for a long time without any issues.

- If you take the same 5 bots in a cluster and start shooting at them, the server will crash within 30 seconds, regardless of the amount of bots you have added. I reran this test on multiple maps and the results are the same.

My last run caused issues with <TemporarilyDisableCollisions> in /home/runner/work/MatchZy/MatchZy/PracticeMode.ts line 1013

`10:55:51 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MatchZy.MatchZy.<>c__DisplayClass268_0.<TemporarilyDisableCollisions>b__0() in /home/runner/work/MatchZy/MatchZy/PracticeMode.cs:line 1013
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100`
   
This was output several times in the docker container logs before the server died.

So I cloned your code, commented out everything in public void TemporarilyDisableCollisions(CCSPlayerController p1, CCSPlayerController p2) on line 999 in PracticeMode.cs, complied and replaced it with my official version and reran everything.

I didnt manage to get the server to die once after this, so there is something happening within this function which causes the server to die.

Hopefully this will give you something to reproduce this issue. Please let me know if I can be of more assistance.

**Comment by BnanZ0** [comment]
@mortenlein 
It seems like the timer went wrong inside "TemporarilyDisableCollisions" while multiple bots were repeatedly spawning, specifically these two codes.
```
collisionGroupTimer?.Kill();
collisionGroupTimer = AddTimer(0.1f, () =>
```
I changed it to Dictionary and the server didn't crash anymore.
```
var TempIndex = collisionGroupTimerIndex;
collisionGroupTimerDictionary[TempIndex] = AddTimer(0.1f, () =>
{
    try
    {
        if (!p1p.IsValid || !p2p.IsValid || !p1p.Value.IsValid || !p2p.Value.IsValid)
        {
            Log($"player handle invalid p1p {p1p.Value.IsValid} p2p {p2p.Value.IsValid}");
            collisionGroupTimerDictionary[TempIndex]?.Kill();
            return;
        }

        if (!DoPlayersCollide(p1p.Value, p2p.Value))
        {
            // Once they no longer collide 
            p1p.Value.Collision.CollisionAttribute.CollisionGroup = (byte)CollisionGroup.COLLISION_GROUP_PLAYER_MOVEMENT;
            p1p.Value.Collision.CollisionGroup = (byte)CollisionGroup.COLLISION_GROUP_PLAYER_MOVEMENT;
            p2p.Value.Collision.CollisionAttribute.CollisionGroup = (byte)CollisionGroup.COLLISION_GROUP_PLAYER_MOVEMENT;
            p2p.Value.Collision.CollisionGroup = (byte)CollisionGroup.COLLISION_GROUP_PLAYER_MOVEMENT;
            // TODO: call CollisionRulesChanged
            collisionGroupTimerDictionary[TempIndex]?.Kill();
        }
    }
    catch
    {
        collisionGroupTimerDictionary[TempIndex]?.Kill();
    }
}, TimerFlags.REPEAT | TimerFlags.STOP_ON_MAPCHANGE);
collisionGroupTimerIndex++;
if (collisionGroupTimerIndex > 100) collisionGroupTimerIndex = 0;
```

**Comment by mortenlein** [comment]
I'll try this to verify your findings, good work
